student_sysday2完整版/student_sys/student_sys/urls.py
from django.contrib import admin
from django.conf.urls import url

from student.views import index,stuadd,login,outlogin,zhuce,editstu,delstu

urlpatterns = [
    url(r'^$', index,name="index"),
    url(r'^stuadd',stuadd,name="stuadd"),
    url(r'^login',login,name="login"),
    url(r'^outlogin',outlogin,name="outlogin"),
    url(r'^zhuce',zhuce,name="zhuce"),
    url(r'editstu',editstu,name="editstu"),
    url(r'delstu',delstu,name="delstu"),
    url(r'^admin/', admin.site.urls),
]

student_sysday2完整版/student_sys/student/models.py
from django.db import models


class Student(models.Model):
    SEX_ITEMS = [
        (1,'男'),
        (2,'女'),
        (0,'未知'),        
    ]
    
    STATUS_ITEMS=[
        (0,'申请'),
        (1,'通过'),
        (2,'拒绝'),        
    ]
    
    
    name = models.CharField(max_length=128,verbose_name="姓名")
    sex = models.IntegerField(choices=SEX_ITEMS, verbose_name="性别")
    profession = models.CharField(max_length=128,verbose_name="职业")
    email = models.EmailField(verbose_name="Email")
    qq = models.CharField(max_length=128,verbose_name="QQ")
    phone = models.CharField(max_length=128,verbose_name="电话")
    status = models.IntegerField(choices=STATUS_ITEMS,default=0,verbose_name="审核状态")
    created_time = models.DateTimeField(auto_now_add=True,editable=False,verbose_name="创建时间")
    
    def __str__(self):
        return '<Student:{}>'.format(self.name)
    
    class Meat:
        verbose_name = verbose_name_plural = "学员信息"
        
        
class Users(models.Model):
    username = models.CharField(max_length=30)
    userpwd = models.CharField(max_length=30)

student_sysday2完整版/student_sys/student/forms.py
# -*- coding: utf-8 -*-

from django import forms
from .models import Student


class StudentForm(forms.ModelForm):
    def clean_qq(self):
            cleaned_data = self.cleaned_data['qq']
            if not cleaned_data.isdigit():
                return forms.ValidationError('必须时数字')
            return int(cleaned_data)
        
    class Meta:
            model = Student
            fields  = ( 'name','sex','profession','status','email','qq','phone')

    

student_sysday2完整版/student_sys/student/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render,redirect
from .models import Student,Users

from django.urls import reverse
from .forms import StudentForm

from functools import wraps

def check_login(f):
    @wraps(f)
    def inner(request,*arg,**kwargs):
        if request.session.get('is_login') == '1':
            return f(request, *arg, **kwargs)
        else:
            return redirect('/login/')
    return inner



# 首页显示学生
@check_login
def index(request):
    
    uid = request.session["userid"]
    u = Users.objects.filter(id=uid)
        
    
    
    allstu = Student.objects.all()
            
    context = {
    
            "stulist":allstu,
            "username":u[0].username
    }

    return render(request, 'index.html', context = context)


# 新增学生的方法
@check_login
def stuadd(request):
    
    if request.method == "POST":
        form = StudentForm(request.POST)        
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('index'))
    else:
        form = StudentForm()
        
    context = {
    
            "form": form,
    }
            
    
    # 跳转页面
    return render(request, 'stuadd.html', context = context)


# 用户登录
def login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        userpwd = request.POST.get("userpwd")
        
        u = Users.objects.filter(username=username,userpwd=userpwd)
        if u:
            request.session["is_login"] = "1"
            request.session["userid"] = u[0].id
            return redirect('/')
    
    return render(request,'login.html')


def outlogin(request):
    request.session['is_login'] = "0"
    return render(request,'login.html')


def zhuce(request):
    if request.method == "POST":
        username = request.POST.get("username")
        userpwd = request.POST.get("userpwd")
        u = Users()
        u.username = username
        u.userpwd = userpwd
        u.save()
        return render(request,'login.html')
    
    return render(request,'zhuce.html')
    

#修改
def editstu(request):
    
    
    if request.method == "POST":
        stuid = request.POST.get("stuid")
        u = Student.objects.filter(id=stuid)

        form = StudentForm(request.POST,instance=u[0])
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('index'))
    else:
        stuid = request.GET.get("stuid")
        u = Student.objects.filter(id=stuid)
        form = StudentForm(instance = u[0])
        
    context = {
    
            "form": form,
            "stuid":stuid
    }

    # 跳转页面
    return render(request, 'editstu.html', context = context)
    
  
 #删除
def delstu(request):
     stuid = request.GET.get("stuid")
     u = Student.objects.filter(id=stuid)
     u[0].delete()
     return HttpResponseRedirect(reverse('index'))
    
    
    
    
    
    
    
    
    
    
    
    
    

student_sysday2完整版/student_sys/student/templates/editstu.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>学生修改</title>
		<link rel="stylesheet" href="../static/css/mycss.css">
		
	</head>
	<body>
	
		<form action="/editstu" method="post">
           {% csrf_token %}
           <table>
               <tr><td>姓名</td><td>{{ form.name }}</td></tr>
               <tr><td>性别</td><td>{{ form.sex }}</td></tr>
               <tr><td>职业</td><td>{{ form.profession }}</td></tr>
               <tr><td>审核状态</td><td>{{ form.status }}</td></tr>
               <tr><td>邮箱</td><td>{{ form.email }}</td></tr>
               <tr><td>qq</td><td>{{ form.qq }}</td></tr>
               <tr><td>电话</td><td>{{ form.phone }}</td></tr>
           </table>
           
           <input type="hidden" name="stuid"  value="{{ stuid }}" />
           
           <input type="submit" value="保存" />
       </form>

	</body>
</html>

student_sysday2完整版/student_sys/student/templates/index.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title></title>
		<link rel="stylesheet" href="../static/css/mycss.css">
		
	</head>
	<body>
	
    	欢迎{{ username }}登录  <a href="/outlogin">安全退出</a>
    	<hr>
    	<br>
	
		{% for stu in stulist  %}
		
		 <li>
    		 {{ stu.name }} - {{ stu.get_status_display }} 
    		 {{stu.get_sex_display}} 
    		 {{ stu.profession }} 
    		 
    		 <a href="/editstu?stuid={{ stu.id }}">修改</a>
    		 <a href="/delstu?stuid={{ stu.id }}">删除</a>
    		 
        </li>
		
		{% endfor %}

		<a href="/stuadd">新增学生</a>
	</body>
</html>

student_sysday2完整版/student_sys/student/templates/login.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title></title>
	</head>
	<body>
		
		<form action="/login/" method="post">
			///{% csrf_token %}///
			用户名：<input type="text" name="username" value="" /><br>
			密码:<input type="password" name="userpwd"  value="" /><br>
			<input type="submit" value="登录"/> <a href="/zhuce/">如果您还没有账号，请注册</a>
		</form>
		
	</body>
</html>

student_sysday2完整版/student_sys/student/templates/stuadd.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>学生的新增</title>
		<link rel="stylesheet" href="../static/css/mycss.css">
		
	</head>
	<body>
	
		<form action="/stuadd" method="post">
           {% csrf_token %}
           <table>
               <tr><td>姓名</td><td>{{ form.name }}</td></tr>
               <tr><td>性别</td><td>{{ form.sex }}</td></tr>
               <tr><td>职业</td><td>{{ form.profession }}</td></tr>
               <tr><td>审核状态</td><td>{{ form.status }}</td></tr>
               <tr><td>邮箱</td><td>{{ form.email }}</td></tr>
               <tr><td>qq</td><td>{{ form.qq }}</td></tr>
               <tr><td>电话</td><td>{{ form.phone }}</td></tr>
           </table>
           <input type="submit" value="添加" />
       </form>

	</body>
</html>

student_sysday2完整版/student_sys/student/templates/zhuce.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>新用户注册</title>
	</head>
	<body>
		
		<form action="/zhuce" method="post">
			{% csrf_token %}
			用户名：<input type="text" name="username" value="" /><br>
			密码:<input type="password" name="userpwd"  value="" /><br>
			再次输入密码:<input type="password"   value="" /><br>
			<input type="submit" value="注册"/>
		</form>
		
	</body>
</html>